global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "todolist-api-prod"
    metrics_path: "/internal/actuator/prometheus"
    static_configs:
      - targets: ["todoapp:8082"] # ← FIX: spring_app → todoapp
    scrape_interval: 10s
    scrape_timeout: 5s
